#include QMK_KEYBOARD_H
#define VENDOR_ID 0x2345
#define PRODUCT_ID 0x1535
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT(
        RGB_MODE_RAINBOW,   RGB_MODE_RAINBOW,   RGB_MODE_RAINBOW,   RGB_MODE_RAINBOW,
        RGB_VAD,   RGB_MODE_RAINBOW,   RGB_MODE_RAINBOW,   RGB_MODE_RAINBOW,
        RGB_HUI,   KC_B,   KC_C,   KC_D
        
    ),
    [1] = LAYOUT(
        RGB_MODE_RAINBOW,   RGB_MODE_RAINBOW,   RGB_MODE_RAINBOW,   RGB_MODE_RAINBOW,
        RGB_VAD,   RGB_MODE_RAINBOW,   RGB_MODE_RAINBOW,   RGB_MODE_RAINBOW,
        RGB_HUI,   KC_B,   KC_C,   KC_D
        
    ),
    [2] = LAYOUT(
        RGB_MODE_RAINBOW,   RGB_MODE_RAINBOW,   RGB_MODE_RAINBOW,   RGB_MODE_RAINBOW,
        RGB_VAD,   RGB_MODE_RAINBOW,   RGB_MODE_RAINBOW,   RGB_MODE_RAINBOW,
        RGB_HUI,   KC_B,   KC_C,   KC_D
        
    ),
    [3] = LAYOUT(
        RGB_MODE_RAINBOW,   RGB_MODE_RAINBOW,   RGB_MODE_RAINBOW,   RGB_MODE_RAINBOW,
        RGB_VAD,   RGB_MODE_RAINBOW,   RGB_MODE_RAINBOW,   RGB_MODE_RAINBOW,
        RGB_HUI,   KC_B,   KC_C,   KC_D
        
    ),
};
